config/routes.rb
Rails.application.routes.draw do
  mount Api::Base, at: "/"

  resources :customers
  resources :cards, only: %i[index check]
  post 'cards/check'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cards#index"
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  include ActiveModel::Validations
  validates_with CardValidator

  validates :number, presence: true

  belongs_to :customer

  def type
    if black?
      'Black'
    elsif red?
      'Red'
    elsif green?
      'Green'
    elsif blue?
      'Blue'
    end
  end

  private

  def black?
    number.start_with?('60141') && (number.length == 17 || number.length == 16)
  end

  def red?
    valid_rgb_length? && number.start_with?('6014352')
  end

  def green?
    valid_rgb_length? && green_range.member?(number.to_i)
  end

  def blue?
    valid_rgb_length? && valid_start?
  end

  def valid_rgb_length?
    number.length == 16
  end

  def green_range
    6_014_355_526_000_000..6_014_355_529_000_001
  end

  def valid_start?
    number.start_with?('6014')
  end
end

app/controllers/api/v1/cards.rb
module Api
  module V1
    class Cards < Grape::API
      include Api::V1::Defaults

      helpers do
        def current_user
          @current_user ||= Customer.first #User.authorize!
        end

        def authenticate
          error('401 error', 401) unless current_user
        end
      end

      resource :cards do
        desc 'Return a card balance'
        params do
          requires :id, type: String, desc: 'ID of the card'
        end
        get ':id' do
          Card.where(number: permitted_params[:number]).first!
        end

        desc 'add balance'
        params do
          requires :number, type: String, desc: 'ID of the card'
        end

        post do
          # authenticate
          # logic for adding balance
        end
        
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  def check
    @cards = card_list
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.fetch(:card, {})
    end

    def card_list
      params[:cards].split("\n").each_with_object([]) do |card_no, cards|
        card_no = card_no.gsub!(/\s/, "")
        puts card_no.inspect
        card = Card.new(number: card_no)
        cards << {
          type: card.type,
          number: card.number,
          status: card.valid?
        }
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/check.html.erb
<main class="container">

  <%= turbo_frame_tag 'validated_turbo_tag' do %>
    <div class="header">
      cards
    </div>

    <ul>
    <% @cards.each do |card| %>
      <li>
        <%= card[:type] ? "Fly Buys #{card[:type].capitalize}" : 'Unknown' %>
        <%= card[:number] %> 
        (<%= card[:status] ? 'valid' : 'invalid' %>)
      </li>
    <% end %>
    </ul>
  <% end %>
</main>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<%= turbo_frame_tag 'card_turbo_tag' do %>
  <%= form_tag '/cards/check', data: { turbo_frame: 'validated_turbo_tag' } do %>
    <%= text_area_tag :cards, nil, size: '100*100' %>
    <%= submit_tag 'check' %>
  <% end %>
<% end %>

<%= link_to 'reset', cards_path, data: { target: '_top' } %>
<hr/>

<%= turbo_frame_tag 'validated_turbo_tag' do %>
  validated turbo tag
<% end %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>